"""Authoritative vocabulary for the bounded Assume/Guarantee profile.

These are serialized strings, so the module intentionally exposes strings and
ordered tuples rather than Enums.  Generators, checkers, assurance routing and
evaluators all import the same values without changing archived JSON shapes.
"""
from __future__ import annotations

from typing import Mapping, Tuple


TIMED_PATTERN = "TRIGGERED_TIMED_FAILSAFE_RESPONSE"
THRESHOLD_PATTERN = "THRESHOLD_TRIGGERED_RESPONSE"
STARTUP_INHIBIT_PATTERN = "STARTUP_INHIBIT"
LOCKED_UNTIL_RELEASE_PATTERN = "LOCKED_UNTIL_AUTHORISED_RELEASE"

TRIGGERED_PATTERNS = (TIMED_PATTERN, THRESHOLD_PATTERN)
INVARIANT_PATTERNS = (STARTUP_INHIBIT_PATTERN, LOCKED_UNTIL_RELEASE_PATTERN)
KNOWN_PATTERNS = (*TRIGGERED_PATTERNS, *INVARIANT_PATTERNS)
UNTIMED_PATTERNS = (THRESHOLD_PATTERN, *INVARIANT_PATTERNS)

STAKEHOLDER_SOURCE_KIND = "STAKEHOLDER"
DERIVED_SOURCE_KIND = "STUDENT_DERIVED_DESIGN_CONSTRAINT"
INVARIANT_SOURCE_KINDS = (STAKEHOLDER_SOURCE_KIND, DERIVED_SOURCE_KIND)

PATTERN_INVARIANT_ROLES: Mapping[str, Tuple[str, ...]] = {
    LOCKED_UNTIL_RELEASE_PATTERN: (
        "locked", "authorisation", "unlocked", "power", "power_on",
    ),
    STARTUP_INHIBIT_PATTERN: ("latch", "reset", "inhibited", "forbidden"),
}

# Diagnostic identity is part of the cross-module failure-routing protocol.
CODE_CONTRACT_INCOMPLETE = "CONTRACT_INCOMPLETE"
CODE_CONTRACT_UNSUPPORTED = "CONTRACT_UNSUPPORTED"
CODE_COMPONENT_GUARANTEE_NONATOMIC = "COMPONENT_GUARANTEE_NONATOMIC"
CODE_SYSTEM_OBSERVATION_BINDING_MISSING = "SYSTEM_OBSERVATION_BINDING_MISSING"
CODE_GUARANTEE_NO_OWNER = "GUARANTEE_NO_OWNER"
CODE_GUARANTEE_MULTIPLE_OWNERS = "GUARANTEE_MULTIPLE_OWNERS"
CODE_ASSUMPTION_UNDISCHARGED = "ASSUMPTION_UNDISCHARGED"
CODE_CIRCULAR_ASSUMPTION = "CIRCULAR_ASSUMPTION"
CODE_UNIT_INCOMPATIBLE = "UNIT_INCOMPATIBLE"
CODE_TIMING_BUDGET_EXCEEDED = "TIMING_BUDGET_EXCEEDED"
CODE_TIMING_BUDGET_MISSING = "TIMING_BUDGET_MISSING"
CODE_DECOMPOSITION_INSUFFICIENT = "DECOMPOSITION_INSUFFICIENT"
CODE_DECOMPOSITION_MISSING = "DECOMPOSITION_MISSING"
CODE_DISCHARGE_EDGE_MISSING = "DISCHARGE_EDGE_MISSING"
CODE_REALIZATION_MISSING = "REALIZATION_MISSING"
CODE_REALIZATION_UNREACHABLE = "REALIZATION_UNREACHABLE"
CODE_REALIZATION_TRIGGER_MISSING = "REALIZATION_TRIGGER_MISSING"
CODE_REALIZATION_ACTION_MISSING = "REALIZATION_ACTION_MISSING"
CODE_OBSERVATION_MISSING = "OBSERVATION_MISSING"
CODE_SOURCE_PROVENANCE_MISSING = "SOURCE_PROVENANCE_MISSING"
CODE_PATTERN_DECLARATION_INCONSISTENT = "PATTERN_DECLARATION_INCONSISTENT"
CODE_PRIORITY_TOPOLOGY_MISSING = "PRIORITY_TOPOLOGY_MISSING"
CODE_PRIORITY_TOPOLOGY_INCOMPLETE = "PRIORITY_TOPOLOGY_INCOMPLETE"
CODE_INVARIANT_SEMANTICS_MISSING = "INVARIANT_SEMANTICS_MISSING"
CODE_INVARIANT_SEMANTICS_INVALID = "INVARIANT_SEMANTICS_INVALID"
CODE_PATTERN_TOPOLOGY_INCOMPLETE = "PATTERN_TOPOLOGY_INCOMPLETE"
