from examples.run_realization_report import retire_stale_parm
from src.prototyping.artifact_provenance import build_run_provenance
from types import SimpleNamespace

from examples.run_sitl_feasibility import (
    _run_single_l2_with_timeout,
    merge_parm_lines,
    parm_freshness,
    planned_l2_specs,
    safety_verification_status,
)
from src.sitl.sitl_bridge import SITLBridge
from src.sysml.lite_model import build_lite_model


def test_safety_verification_status_marks_partial_when_trace_blocked_and_l2_runs():
    status = safety_verification_status(
        [{"req_id": "REQ_SAFE_005", "passed": False}],
        [{"req_id": "REQ_SAFE_003", "passed": False}],
    )

    assert status["status"] == "PARTIAL"
    assert status["l2_passed"] == 0
    assert status["l2_total"] == 1
    assert status["traceability_blocked"] == 1


def test_safety_verification_status_marks_blocked_without_executable_l2():
    status = safety_verification_status(
        [],
        [{"req_id": "REQ_SAFE_003", "passed": False}],
    )

    assert status["status"] == "BLOCKED"
    assert status["traceability_blocked"] == 1


def test_safety_verification_status_marks_pass_and_fail_without_trace_blocks():
    assert safety_verification_status(
        [{"req_id": "REQ_SAFE_005", "passed": True}],
        [],
    )["status"] == "PASS"
    assert safety_verification_status(
        [{"req_id": "REQ_SAFE_005", "passed": False}],
        [],
    )["status"] == "FAIL"
    assert safety_verification_status([], [])["status"] == "NOT_RUN"


def test_single_l2_retries_one_transient_sitl_startup_failure():
    class Bridge:
        _connection_string = "tcp:127.0.0.1:5760"

        def __init__(self):
            self.launches = 0
            self.stops = 0

        def launch_sitl(self, wait_s):
            assert wait_s == 45.0
            self.launches += 1
            return self.launches == 2

        def stop_sitl(self):
            self.stops += 1

        def _run_single_test(self, spec, connection, mavutil_module, fresh_sitl):
            assert connection == self._connection_string
            assert fresh_sitl is True
            return True, "passed after retry"

    bridge = Bridge()
    spec = SimpleNamespace(
        req_id="REQ_SAFE_004",
        inject=SimpleNamespace(kind="set_param"),
    )

    result = _run_single_l2_with_timeout(bridge, spec, timeout_s=10)

    assert result["passed"] is True
    assert result["message"] == "passed after retry"
    assert bridge.launches == 2
    assert bridge.stops == 2  # cleanup after failed attempt + final cleanup


def test_merge_parm_lines_preserves_recommended_design_and_adds_safety_params():
    merged = merge_parm_lines(
        [
            "FRAME_CLASS                    1",
            "BATT_CAPACITY                  22000",
            "SERVO7_FUNCTION                0  # design file value wins",
        ],
        [
            "# generated by linker",
            "FRAME_CLASS                    2  # should not override",
            "GRIP_ENABLE                    1  # safety boot param",
            "GRIP_TYPE                      1",
            "SERVO7_FUNCTION                28  # duplicate should not override",
        ],
    )

    assert "FRAME_CLASS                    1" in merged
    assert "FRAME_CLASS                    2  # should not override" not in merged
    assert "SERVO7_FUNCTION                0  # design file value wins" in merged
    assert "SERVO7_FUNCTION                28  # duplicate should not override" not in merged
    assert "GRIP_ENABLE                    1  # safety boot param" in merged
    assert "GRIP_TYPE                      1" in merged


def test_planned_l2_specs_lists_executable_checks_without_launching_sitl(tmp_path):
    model = build_lite_model(
        """package D {
            requirement def REQ_SAFE_003 {
                doc /* GCS link loss for more than 10 seconds shall trigger safe landing. */
            }
            part def SafetyMonitor {
                attribute commLossTime : Real = 0.0;
                satisfy requirement REQ_SAFE_003;
                state def Monitor {
                    state nominal;
                    state lost;
                    transition initial then nominal;
                    transition gcs first nominal if commLossTime > 10.0 then lost;
                }
            }
        }""",
        model_name="D",
    )
    bridge = SITLBridge(model, output_dir=str(tmp_path))

    planned = planned_l2_specs(bridge)

    # "trigger safe landing" is land-only text → the action-specific LAND entry
    # (RTL is a wrong action for this requirement, not an acceptable fallback).
    assert planned == [{
        "req_id": "REQ_SAFE_003",
        "tier": "L2",
        "inject": "disconnect_gcs",
        "verify": "wait_mode",
        "pre_takeoff_m": 5.0,
        "notes": "GCS loss → LAND at current position (FS_GCS_ENABLE=5); "
                 "requirement mandates landing, RTL is NOT accepted.",
        "model_guard": "commLossTime > 10.0",
    }]


def test_parm_freshness_blocks_bilevel_fallback_leftovers():
    # Latest run produced no recommendation (variation DSE fell back before
    # Phase 8) — an older recommended.parm on disk must be flagged stale.
    fresh, reason = parm_freshness(
        ["BATT_CAPACITY        15065", "FRAME_CLASS          2"],
        {"recommended_design_inputs": None},
    )
    assert fresh is False
    assert "no recommended design" in reason


def test_parm_freshness_detects_design_mismatch_and_accepts_match():
    stale, reason = parm_freshness(
        ["BATT_CAPACITY        15065", "FRAME_CLASS          2"],
        {"recommended_design_inputs": {"battery_capacity_mah": 22000.0, "rotor_count": 4}},
    )
    assert stale is False
    assert "BATT_CAPACITY" in reason

    lines = ["BATT_CAPACITY        22000", "FRAME_CLASS          1", "# comment"]
    run = {
        "requirements": [],
        "recommended_design_inputs": {"battery_capacity_mah": 22000.0, "rotor_count": 4},
        "realization": None,
    }
    run["artifact_provenance"] = build_run_provenance(
        model_sysml="model", recommended_design=run["recommended_design_inputs"],
        realization=None, requirements=run["requirements"],
        parm_text="\n".join(lines) + "\n", run_id="test-run",
    )
    fresh, reason = parm_freshness(lines, run, model_sysml="model")
    assert fresh is True
    assert "consistent" in reason


def test_parm_freshness_without_run_json_is_rejected():
    fresh, reason = parm_freshness(["BATT_CAPACITY 1"], None)
    assert fresh is False
    assert "required" in reason


def test_retire_stale_parm_renames_leftover_file(tmp_path):
    parm = tmp_path / "recommended.parm"
    parm.write_text("BATT_CAPACITY 15065\n", encoding="utf-8")

    assert retire_stale_parm(str(parm)) is True
    assert not parm.exists()
    assert (tmp_path / "recommended.parm.stale").read_text() == "BATT_CAPACITY 15065\n"
    # nothing left to retire → False, and no crash
    assert retire_stale_parm(str(parm)) is False


def test_coverage_summary_counts_unmapped_requirements(tmp_path):
    from examples.run_sitl_feasibility import coverage_summary

    # REQ_SAFE_003 maps (GCS guard); REQ_CONS_002 (IP54) satisfies a part with no
    # relevant guard/attr → honest unmapped bucket, surfaced so "blocked=0" is
    # not over-read as "everything verified".
    model = build_lite_model(
        """package D {
            requirement def REQ_SAFE_003 {
                doc /* GCS link loss for more than 10 seconds shall trigger safe landing. */
            }
            requirement def REQ_CONS_002 {
                doc /* Enclosures shall meet a minimum IP54 ingress-protection rating. */
            }
            part def SafetyMonitor {
                attribute commLossTime : Real = 0.0;
                satisfy requirement REQ_SAFE_003;
                satisfy requirement REQ_CONS_002;
                state def Monitor {
                    state nominal;
                    state lost;
                    transition initial then nominal;
                    transition gcs first nominal if commLossTime > 10.0 then lost;
                }
            }
        }""",
        model_name="D",
    )
    bridge = SITLBridge(model, output_dir=str(tmp_path))

    stats = coverage_summary(bridge)

    assert stats["satisfied"] == 2
    assert stats["mapped"] == 1
    assert stats["unmapped"] == 1
    assert stats["unmapped_req_ids"] == ["REQ_CONS_002"]
    assert stats["traceability_mismatched"] == 0
