import pytest

from examples.run_realization_report import (
    require_authoritative_functional_closure,
    require_authoritative_runtime,
    retire_stale_parm,
)
from types import SimpleNamespace

from examples.run_sitl_feasibility import (
    _run_single_l2_with_timeout,
    merge_parm_lines,
    parm_freshness,
    planned_l2_specs,
    safety_verification_status,
)
from src.sitl.sitl_bridge import SITLBridge
from src.sysml.lite_model import build_lite_model


def test_status_partial_trace_blocked():
    status = safety_verification_status(
        [{"req_id": "REQ_SAFE_005", "passed": False}],
        [{"req_id": "REQ_SAFE_003", "passed": False}],
    )

    assert status["status"] == "PARTIAL"
    assert status["l2_passed"] == 0
    assert status["l2_total"] == 1
    assert status["traceability_blocked"] == 1


def test_status_blocked_without_l2():
    status = safety_verification_status(
        [],
        [{"req_id": "REQ_SAFE_003", "passed": False}],
    )

    assert status["status"] == "BLOCKED"
    assert status["traceability_blocked"] == 1


def test_status_pass_and_fail():
    assert safety_verification_status(
        [{"req_id": "REQ_SAFE_005", "passed": True}],
        [],
    )["status"] == "PASS"
    assert safety_verification_status(
        [{"req_id": "REQ_SAFE_005", "passed": False}],
        [],
    )["status"] == "FAIL"
    assert safety_verification_status([], [])["status"] == "NOT_RUN"


def test_status_inconclusive():
    status = safety_verification_status([
        {"passed": True, "conclusive": True},
        {"passed": False, "conclusive": False},
    ], [])

    assert status["status"] == "INCONCLUSIVE"
    assert status["l2_inconclusive"] == 1


def test_l2_retries_startup_failure():
    class Bridge:
        _connection_string = "tcp:127.0.0.1:5760"

        def __init__(self):
            self.launches = 0
            self.stops = 0

        def launch_sitl(self, wait_s):
            assert wait_s == 45.0
            self.launches += 1
            return self.launches == 2

        def stop_sitl(self):
            self.stops += 1

        def _run_single_test(self, spec, connection, mavutil_module, fresh_sitl):
            assert connection == self._connection_string
            assert fresh_sitl is True
            return True, "passed after retry"

    bridge = Bridge()
    spec = SimpleNamespace(
        req_id="REQ_SAFE_004",
        inject=SimpleNamespace(kind="set_param"),
    )

    result = _run_single_l2_with_timeout(bridge, spec, timeout_s=10)

    assert result["passed"] is True
    assert result["message"] == "passed after retry"
    assert bridge.launches == 2
    assert bridge.stops == 2


def test_merge_parm_lines_design_wins():
    merged = merge_parm_lines(
        [
            "FRAME_CLASS                    1",
            "BATT_CAPACITY                  22000",
            "SERVO7_FUNCTION                0  # design file value wins",
        ],
        [
            "# generated by linker",
            "FRAME_CLASS                    2  # should not override",
            "GRIP_ENABLE                    1  # safety boot param",
            "GRIP_TYPE                      1",
            "SERVO7_FUNCTION                28  # duplicate should not override",
        ],
    )

    assert "FRAME_CLASS                    1" in merged
    assert "FRAME_CLASS                    2  # should not override" not in merged
    assert "SERVO7_FUNCTION                0  # design file value wins" in merged
    assert "SERVO7_FUNCTION                28  # duplicate should not override" not in merged
    assert "GRIP_ENABLE                    1  # safety boot param" in merged
    assert "GRIP_TYPE                      1" in merged


def test_planned_l2_specs_no_sitl(tmp_path):
    model = build_lite_model(
        """package D {
            requirement def REQ_SAFE_003 {
                doc /* GCS link loss for more than 10 seconds shall trigger safe landing. */
            }
            part def SafetyMonitor {
                attribute commLossTime : Real = 0.0;
                satisfy requirement REQ_SAFE_003;
                state def Monitor {
                    state nominal;
                    state lost;
                    transition initial then nominal;
                    transition gcs first nominal if commLossTime > 10.0 then lost;
                }
            }
        }""",
        model_name="D",
    )
    bridge = SITLBridge(model, output_dir=str(tmp_path))

    planned = planned_l2_specs(bridge)

    # "trigger safe landing" is land-only text -> the action-specific LAND entry;
    # RTL is the wrong action here, not a fallback.
    assert planned == [{
        "req_id": "REQ_SAFE_003",
        "tier": "L2",
        "inject": "disconnect_gcs",
        "verify": "wait_mode",
        "pre_takeoff_m": 5.0,
        "notes": "GCS loss → LAND at current position (FS_GCS_ENABLE=5); "
                 "requirement mandates landing, RTL is NOT accepted.",
        "model_guard": "commLossTime > 10.0",
    }]


def test_parm_freshness_no_design():
    # Latest run produced no recommendation (variation DSE fell back before Phase 8),
    # so an older recommended.parm on disk is flagged stale.
    fresh, reason = parm_freshness(
        ["BATT_CAPACITY        15065", "FRAME_CLASS          2"],
        {"recommended_design_inputs": None},
    )
    assert fresh is False
    assert "no recommended design" in reason


def test_parm_freshness_mismatch():
    stale, reason = parm_freshness(
        ["BATT_CAPACITY        15065", "FRAME_CLASS          2"],
        {"recommended_design_inputs": {"battery_capacity_mah": 22000.0, "rotor_count": 4}},
    )
    assert stale is False
    assert "BATT_CAPACITY" in reason

    lines = ["BATT_CAPACITY        22000", "FRAME_CLASS          1", "# comment"]
    run = {
        "requirements": [],
        "recommended_design_inputs": {"battery_capacity_mah": 22000.0, "rotor_count": 4},
        "realization": None,
    }
    run["run_id"] = "test-run"
    fresh, reason = parm_freshness(lines, run, model_sysml="model")
    assert fresh is True
    assert "consistent" in reason


def test_parm_freshness_needs_run_json():
    fresh, reason = parm_freshness(["BATT_CAPACITY 1"], None)
    assert fresh is False
    assert "required" in reason


def test_retire_stale_parm_renames(tmp_path):
    parm = tmp_path / "recommended.parm"
    parm.write_text("BATT_CAPACITY 15065\n", encoding="utf-8")

    assert retire_stale_parm(str(parm)) is True
    assert not parm.exists()
    assert (tmp_path / "recommended.parm.stale").read_text() == "BATT_CAPACITY 15065\n"
    assert retire_stale_parm(str(parm)) is False


def test_publication_blocks_functional_gap():
    broken = """package D {
        requirement def REQ_FUNC_008 {
            doc /* Transmit a post-flight health report within 5 seconds of landing completion. */
        }
        part def CommunicationSystem {
            action def transmitHealthReport { }
            satisfy requirement REQ_FUNC_008;
        }
    }"""

    with pytest.raises(RuntimeError, match="REQ_FUNC_008"):
        require_authoritative_functional_closure(broken)


def test_publication_accepts_closed():
    closed = """package D {
        action def AutomatedLandingCompleted { }
        requirement def REQ_FUNC_008 {
            doc /* Transmit a post-flight health report within 5 seconds of landing completion. */
        }
        part def CommunicationSystem {
            attribute maxHealthReportLatency : Real = 5.0 [s];
            attribute currentHealthReportLatency : Real = 0.0 [s];
            action def transmitHealthReport { }
            assert constraint healthReportLatencyBound {
                currentHealthReportLatency <= maxHealthReportLatency
            }
            state def PostFlightHealthReportMachine {
                state Waiting;
                state Sent { entry action report : transmitHealthReport; }
                transition initial then Waiting;
                transition transmitReportAfterLanding first Waiting
                    accept AutomatedLandingCompleted then Sent;
            }
            satisfy requirement REQ_FUNC_008;
        }
    }"""

    assert require_authoritative_functional_closure(closed) == []


def test_runtime_requires_syside(monkeypatch):
    from src.simulation import syntax_checker
    from src.sysml import lite_model

    monkeypatch.setattr(syntax_checker, "_SYSIDE_OK", False)
    monkeypatch.setattr(lite_model, "_SYSIDE_OK", False)

    with pytest.raises(RuntimeError, match="Syside Python API is unavailable"):
        require_authoritative_runtime()


def test_coverage_counts_unmapped(tmp_path):
    from examples.run_sitl_feasibility import coverage_summary

    # REQ_SAFE_003 maps (GCS guard); REQ_CONS_002 (IP54) satisfies a part with no
    # relevant guard/attr -> unmapped bucket, surfaced so "blocked=0" is not read
    # as "everything verified".
    model = build_lite_model(
        """package D {
            requirement def REQ_SAFE_003 {
                doc /* GCS link loss for more than 10 seconds shall trigger safe landing. */
            }
            requirement def REQ_CONS_002 {
                doc /* Enclosures shall meet a minimum IP54 ingress-protection rating. */
            }
            part def SafetyMonitor {
                attribute commLossTime : Real = 0.0;
                satisfy requirement REQ_SAFE_003;
                satisfy requirement REQ_CONS_002;
                state def Monitor {
                    state nominal;
                    state lost;
                    transition initial then nominal;
                    transition gcs first nominal if commLossTime > 10.0 then lost;
                }
            }
        }""",
        model_name="D",
    )
    bridge = SITLBridge(model, output_dir=str(tmp_path))

    stats = coverage_summary(bridge)

    assert stats["satisfied"] == 2
    assert stats["mapped"] == 1
    assert stats["unmapped"] == 1
    assert stats["unmapped_req_ids"] == ["REQ_CONS_002"]
    assert stats["traceability_mismatched"] == 0
